name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Change this to your deployment branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js 20.x (Force Update)
      run: |
        sudo apt-get purge -y nodejs npm || true
        curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
        sudo apt-get install -y nodejs
        node -v
        npm -v

    - name: Install Firebase CLI
      run: npm install -g firebase-tools@latest

    - name: Deploy to Firebase Hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: |
        firebase deploy --only hosting --project iot-dtu
